apiVersion: v1
kind: Service
metadata:
  name: goserver-service
spec:
  selector:
    app: myapp
  type: NodePort
  ports:
  - name: goserver-service
    port: 80
    targetPort: 8090
    protocol: TCP
    nodePort: 30001 #30.000-32.767
    